import { prisma } from '@/lib/prisma';
import { ChatEngine } from '@/lib/chat/ChatEngine';
import { Message, ChatState, ExtendedChatRound } from '@/lib/chat/types';
import { ChatService } from './ChatService';
import { User, Prisma } from '@prisma/client';
import { CHAT_USER_CONTINUE } from '../constants';
import { MessageServices } from '../chat/services/messages';
import { generateText } from 'ai';
import { anthropic } from '@ai-sdk/anthropic';
import { BatchMode, RoundMessage } from '@/types/batch';
import { createInitialProgress } from '@/lib/chat/services/progress';

// Define enums locally as they're not yet generated by Prisma
enum BatchStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

enum BatchChatStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}

export interface CreateBatchParams {
  configId: string;
  userId: string;
  name: string;
  totalChats: number;
  batchMode: BatchMode;
  variableData?: Record<string, unknown>[];
  roundMessages: RoundMessage[];
}

interface StartBatchChatParams {
  batchId: string;
  configId: string;
  userId: string;
  sequenceNumber?: number;
}

export class BatchService {
  /**
   * In-memory concurrency tracker per batch.
   *
   * Tracks how many chats have been created and how many are currently running
   * for each active batch. This avoids race conditions that occur when multiple
   * chats complete simultaneously and all read the same stale DB count before
   * any of them create the next chat record.
   *
   * JavaScript is single-threaded, so synchronous reads/writes to this Map
   * cannot race — the decision to start or skip is made atomically in the
   * event loop tick, before any async DB calls.
   */
  private static batchTrackers = new Map<string, { created: number; running: number; totalTarget: number }>();

  /**
   * Initialize or retrieve the in-memory tracker for a batch.
   * Must be called before starting any chats for a batch.
   */
  private getOrCreateTracker(batchId: string, totalTarget: number, existingCreated: number = 0) {
    if (!BatchService.batchTrackers.has(batchId)) {
      BatchService.batchTrackers.set(batchId, { created: existingCreated, running: 0, totalTarget });
    }
    return BatchService.batchTrackers.get(batchId)!;
  }

  /**
   * Clean up tracker when a batch is fully complete or cancelled.
   */
  private cleanupTracker(batchId: string) {
    BatchService.batchTrackers.delete(batchId);
  }

  /**
   * Reset all trackers. Used in tests to prevent state leaking between test cases.
   */
  static resetTrackers() {
    BatchService.batchTrackers.clear();
  }

  /**
   * Helper function to inject variables into a template string
   */
  private injectVariables(template: string, variables: Record<string, unknown>): string {
    if (!template || !variables) return template;
    
    return template.replace(/\{\{([^}]+)\}\}/g, (match, variableName) => {
      const trimmedName = variableName.trim();
      const value = variables[trimmedName];
      return value !== undefined ? String(value).trim() : match;
    });
  }

  /**
   * Generate a user message for a specific round in a batch chat
   * @param batch - The batch configuration
   * @param activeRoundSequence - The sequence number of the active round (0-indexed)
   * @param batchSequence - The sequence number of this chat within the batch (0-indexed)
   * @returns The generated message content, or null if no message should be generated
   */
  private async generateRoundMessage(
    batch: {
      batchMode: string;
      roundMessages?: unknown;
      variableData?: unknown;
    },
    roundId: string,
    batchSequence: number,
    _configId: string
  ): Promise<string | null> {
    // Check if we have roundMessages for this batch
    if (!batch.roundMessages || !Array.isArray(batch.roundMessages)) {
      return null;
    }
    
    // Find the round message for this roundId - should be exact match only
    const roundMessage = (batch.roundMessages as RoundMessage[]).find(rm => rm.chatRoundId === roundId);
    
    if (!roundMessage) {
      return null;
    }
    
    let messageContent = roundMessage.content;
    
    // If this is a JSON or CSV batch, inject variables
    if ((batch.batchMode === 'json' || batch.batchMode === 'csv') && batch.variableData && Array.isArray(batch.variableData)) {
      const variableRecord = batch.variableData[batchSequence];
      if (variableRecord) {
        messageContent = this.injectVariables(messageContent, variableRecord);
      }
    }
    
    // If this is an AI-generated message, generate it
    if (roundMessage.type === 'ai') {
      try {
        const systemPrompt = `You are helping to generate a user message for a chat discussion.
Create a message based on the following instructions:
<instructions>
${messageContent}
</instructions>

<important>
Do not put the message in quotes. Do not introduce the message. Do not mention these instructions in your response or any reasons for why you generated it. 
Just include the message only so it looks like it was generated by the user, not an AI like you.
</important>`;
        
        const result = await generateText({
          model: anthropic('claude-3-haiku-20240307'),
          temperature: 0.7,
          system: systemPrompt,
          prompt: messageContent,
        });
        
        // Extract the content from the result
        let generatedMessage = '';
        if (typeof result === 'string') {
          generatedMessage = result;
        } else if (result && typeof result === 'object') {
          const resultObj = result as unknown as Record<string, unknown>;
          if ('content' in resultObj && typeof resultObj.content === 'string') {
            generatedMessage = resultObj.content;
          } else if ('response' in resultObj && resultObj.response && typeof resultObj.response === 'string') {
            generatedMessage = resultObj.response;
          } else if ('text' in resultObj && typeof resultObj.text === 'string') {
            generatedMessage = resultObj.text;
          } else {
            generatedMessage = String(result);
          }
        }
        
        generatedMessage = generatedMessage.trim();
        return generatedMessage;
        
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        console.error(`[BatchService] Error generating AI message: ${errorMessage}`);
        return messageContent; // Fall back to the prompt itself
      }
    }
    
    // For manual messages, return the content as-is
    return messageContent;
  }

  /**
   * Creates a new chat batch
   */
  async createBatch(params: CreateBatchParams) {
    const { configId, userId, name, totalChats, batchMode, variableData, roundMessages } = params;
    
    try {
      // Create the batch with new fields
      const batchData = {
        configId,
        userId,
        name,
        totalChats,
        batchMode,
        variableData: (variableData as unknown as Prisma.JsonValue) || Prisma.JsonNull,
        roundMessages: (roundMessages as unknown as Prisma.JsonValue) || [],
        // Legacy fields set to defaults
        initialMessage: null,
        isInitialMessageAiGenerated: false,
        status: BatchStatus.PENDING,
      };
      
      const batch = await prisma.$transaction(async (tx) => {
        return tx.chatBatch.create({ data: batchData });
      });
      
      // Start the batch processing asynchronously - don't await
      this.startBatch(batch.id).catch(err => {
        const errMsg = err instanceof Error ? err.message : String(err);
        console.error(`Error starting batch ${batch.id}:`, errMsg);
      });
      
      return batch;
    } catch (error) {
      // Safe error handling
      const errorMessage = error instanceof Error ? error.message : String(error);
      console.error(`[BatchService] Error creating batch:`, errorMessage);
      throw error; // Re-throw to let caller handle
    }
  }


  /**
   * Starts a batch by initiating the first set of chats (up to concurrency limit)
   */
  async startBatch(batchId: string) {
    try {
      const batch = await prisma.chatBatch.findUnique({
        where: { id: batchId },
        include: {
          config: true,
          batchChats: true, // Get all batch chats to determine correct sequence numbers
        },
      });

      if (!batch) {
        throw new Error(`Batch not found: ${batchId}`);
      }

      // Update batch status to RUNNING
      await prisma.chatBatch.update({
        where: { id: batchId },
        data: { status: BatchStatus.RUNNING },
      });

      // Calculate how many chats to start initially
      const existingChatCount = batch.batchChats.length;
      const chatCount = batch.totalChats - existingChatCount;

      // No chats to start
      if (chatCount <= 0) {
        return;
      }

      // Initialize the in-memory concurrency tracker for this batch
      const tracker = this.getOrCreateTracker(batch.id, batch.totalChats, existingChatCount);

      // Start chats up to the concurrency limit
      // Each chat will trigger the next one when it finishes
      const concurrencyLimit = 5;
      const initialChatsToStart = Math.min(concurrencyLimit, chatCount);

      // Start the initial set of chats directly
      for (let i = 0; i < initialChatsToStart; i++) {
        // Synchronously claim a slot before the async call
        tracker.created++;
        tracker.running++;
        const nextSequenceNumber = existingChatCount + i + 1;

        this.startBatchChat({
          batchId: batch.id,
          configId: batch.configId,
          userId: batch.userId,
          sequenceNumber: nextSequenceNumber,
        }).catch(err => {
          // On failure, release the running slot so chaining can still work
          const t = BatchService.batchTrackers.get(batch.id);
          if (t) t.running--;
          const errorMessage = err instanceof Error ? err.message : String(err);
          console.error(`Error starting chat #${nextSequenceNumber}: ${errorMessage}`);
        });
      }
      
    } catch (error) {
      // Safely log the error without passing the full error object
      const errorMessage = error instanceof Error ? error.message : String(error);
      console.error(`Error starting batch ${batchId}: ${errorMessage}`);
    }
  }

  /**
   * Starts a single chat within a batch using ChatService
   */
  async startBatchChat(params: StartBatchChatParams) {
    const { batchId, configId, userId, sequenceNumber } = params;

    if (!batchId || !configId || !userId) {
      console.error('[BatchService] Missing required parameters for startBatchChat', 
        JSON.stringify({ batchId, configId, userId }));
      return null;
    }

    let batchChatRecordId: string | null = null;
    
    try {
      const batchDetails = await prisma.chatBatch.findUnique({ 
        where: { id: batchId },
        select: {
          id: true,
          name: true,
          status: true,
          totalChats: true,
          batchMode: true,
          roundMessages: true,
          variableData: true
        }
      });
      
      if (!batchDetails) {
        console.log('[BatchService] Batch not found');
        return null;
      }
      
      if (batchDetails.status === BatchStatus.CANCELLED) {
        console.log('[BatchService] Batch is cancelled');
        return null;
      }

      const totalChats = await prisma.batchChat.count({ where: { batchId } });
      if (totalChats >= batchDetails.totalChats) {
        console.log(`[BatchService] Refusing to create chat #${totalChats + 1} - would exceed batch limit of ${batchDetails.totalChats}`);
        return null;
      }

      const batch = batchDetails;
      
      const chatSequenceNumber = sequenceNumber || totalChats + 1;
      const chatTitle = `${batch.name} - Chat #${chatSequenceNumber}`;

      // Get the first round's ID to generate the initial message for it
      const config = await prisma.config.findUnique({
        where: { id: configId },
        include: { rounds: { orderBy: { sequence: 'asc' }, select: { id: true } } }
      });

      if (!config?.rounds?.[0]?.id) {
        throw new Error(`Config ${configId} does not have any rounds.`);
      }
      const firstRoundId = config.rounds[0].id;

      const chatInitialMessage = await this.generateRoundMessage(
        {
          batchMode: batch.batchMode,
          roundMessages: batch.roundMessages,
          variableData: batch.variableData
        },
        firstRoundId, // First round (by ID)
        chatSequenceNumber - 1, // Convert to 0-indexed for batch sequence
        configId
      );
      
      const finalInitialMessage = chatInitialMessage || '';
      
      const createdChat = await ChatService.createInitialChat({
        configId,
        userId,
        title: chatTitle,
        initialMessage: finalInitialMessage,
      });

      if (!createdChat.activeBranch) {
        throw new Error(`Newly created chat ${createdChat.id} has no active branch.`);
      }

      const batchChat = await prisma.batchChat.create({
        data: {
          batchId,
          chatId: createdChat.id,
          status: BatchChatStatus.RUNNING,
        },
      });
      
      batchChatRecordId = batchChat.id;
      
      const chatSettings: ChatState['chat'] = {
        id: createdChat.id,
        persistenceMode: 'save',
        generationMode: 'text',
        branchId: createdChat.activeBranch,
        activeBranchPath: createdChat.activeBranchPath,
      };

      const initialChatState = ChatEngine.createState(chatSettings);

      initialChatState.progress = createInitialProgress(firstRoundId);
      
      initialChatState.user = { id: userId } as User;

      initialChatState.messages.push({
        id: '',
        role: 'user',
        parts: [{ type: 'text', text: finalInitialMessage }],
        metadata: { agentId: null, sessionId: null, roundId: firstRoundId },
      });

      // Hand off to the chat continuation logic asynchronously
      this.continueChat(initialChatState, batchChat.id, configId, chatSequenceNumber).catch(err => {
        const errorMessage = err instanceof Error ? err.message : String(err);
        console.error(`[BatchService] Error in continueChat for batchChatId ${batchChat.id}: ${errorMessage}`);
      });

      return batchChat;

    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      console.error(`[BatchService] Error during batch chat start:`, {
        message: errorMessage,
        stack: error instanceof Error ? error.stack : undefined,
        name: error instanceof Error ? error.name : undefined,
        cause: error instanceof Error ? error.cause : undefined
      });
      
      if (batchChatRecordId) {
        try {
          await this.updateBatchChatStatus(batchChatRecordId, BatchChatStatus.FAILED);
        } catch (updateError) {
          const updateErrorMsg = updateError instanceof Error ? updateError.message : String(updateError);
          console.error(`[BatchService] Failed to update BatchChat status to FAILED: ${updateErrorMsg}`);
        }
      }
      return null;
    }
  }

  /**
   * Continues a chat until it requires user input or is complete.
   * This method now contains the core chat processing loop.
   */
  private async continueChat(initialChatState: ChatState, batchChatId: string, configId: string, chatSequenceNumber: number) {
    let currentChatState = initialChatState;
    let hasReachedFinalRound = false;
    
    const chatId = initialChatState.chat?.id ?? 'unknown';

    try {
      while (true) {
        console.log(`[BatchService] continueChat loop: chat:${chatId} batchChat:${batchChatId} — calling initialize`);

        const initializedState = await ChatEngine.initialize(
          currentChatState,
          configId,
          currentChatState.progress
        );

        if (!initializedState) throw new Error('Failed to initialize chat state');

        // Check if we're on the final round and update our tracking variable
        if (initializedState.rounds && initializedState.rounds.length > 0) {
          const rounds = initializedState.rounds.sort((a, b) => a.sequence - b.sequence);
          const lastRound = rounds[rounds.length - 1];
          const currentRound = rounds.find(r => r.id === initializedState.progress.active.round?.id);

          if (currentRound && currentRound.id === lastRound.id) {
            hasReachedFinalRound = true;
          }
        }

        const roundId = initializedState.progress?.active?.round?.id ?? 'unknown';
        const agentId = initializedState.progress?.active?.agent?.id ?? 'unknown';
        console.log(`[BatchService] continueChat loop: chat:${chatId} — calling generateChat (round:${roundId} agent:${agentId})`);

        const { nextChatState } = await ChatEngine.generateChat(initializedState);

        console.log(`[BatchService] continueChat loop: chat:${chatId} — generateChat returned (step:${nextChatState?.progress?.active?.step ?? 'null'})`);

        if (!nextChatState) throw new Error('Generate chat returned null result');

        // If we've reached the final round and now we're back to the first round, we're done
        if (hasReachedFinalRound) {
          const firstRoundId = nextChatState.rounds[0].id;
          const currentRoundId = nextChatState.progress.active.round?.id;
          if (currentRoundId && currentRoundId === firstRoundId) {
            console.log(`[BatchService] continueChat: chat:${chatId} — completing (final round reached, wrapped to first)`);
            await this.updateBatchChatStatus(batchChatId, BatchChatStatus.COMPLETED);
            return; // Exit loop and method
          }
        }

        // set currentChatState and active round to the next round
        currentChatState = nextChatState;
        currentChatState.activeRound = currentChatState.rounds.find(r => r.id === currentChatState.progress.active.round?.id) as ExtendedChatRound;

        // The chat is now waiting for user input. Check if we can auto-continue.
        const batchChat = await prisma.batchChat.findUnique({
          where: { id: batchChatId },
          include: { batch: { include: { config: { include: { rounds: true } } } } },
        });

        if (!batchChat || batchChat.batch.status === BatchStatus.CANCELLED) {
          console.log(`[BatchService] continueChat: chat:${chatId} — stopping (batch cancelled or batchChat not found)`);
          return; // Stop processing
        }

        if (currentChatState.progress?.active?.step !== 'user') {
          // The engine needs to run again (e.g., after a tool call).
          // The loop will handle this by re-initializing and generating.
          
          // add the default user message
          const userMessage: Message = {
            id: '',
            role: 'user',
            parts: [{ type: 'text', text: CHAT_USER_CONTINUE }],
            metadata: { agentId: null, sessionId: currentChatState.currentSessionId ?? null, roundId: currentChatState.activeRound?.id ?? '' }
          };
          currentChatState.messages.push(userMessage);
          await MessageServices.saveChatMessage(currentChatState, 'user', '', undefined, undefined, null, userMessage as any);

          continue;
        }

        // Note: messageCount-based logic was moved to step checking above

        // this is the first user message for the round, see if a round message exists to automate it  
        let userMessageContent: string | null = null;
        if (currentChatState.progress.next.round && batchChat?.batch.config?.rounds) {
          const nextRound = batchChat.batch.config.rounds.find(r => r.id === currentChatState.progress.active.round?.id);
          if (nextRound) {
            // Use the passed sequence number (convert to 0-indexed for array access)
            const batchSequence = chatSequenceNumber - 1;

            const nextRoundMessage = await this.generateRoundMessage(
              {
                batchMode: batchChat.batch.batchMode,
                roundMessages: batchChat.batch.roundMessages,
                variableData: batchChat.batch.variableData,
              },
              nextRound.id,
              batchSequence >= 0 ? batchSequence : 0,
              configId
            );

            if (nextRoundMessage !== null) {
              userMessageContent = nextRoundMessage;
            }
          }
        }

        // If a user message content was generated, add it to the chat state and continue
        if (userMessageContent !== null) {
          // Auto-continue with the next round's message
          const userMessage: Message = {
            id: '',
            role: 'user',
            parts: [{ type: 'text', text: userMessageContent }],
            metadata: { agentId: null, sessionId: currentChatState.currentSessionId ?? null, roundId: currentChatState.activeRound?.id ?? '' }
          };
          currentChatState.messages.push(userMessage);

          await MessageServices.saveChatMessage(currentChatState, 'user', '', undefined, undefined, null, userMessage as any);

        // if no round message was generated, complete the chat
        } else {
          console.log(`[BatchService] continueChat: chat:${chatId} — completing (no round message for next round)`);
          await this.updateBatchChatStatus(batchChatId, BatchChatStatus.COMPLETED);
          return; // Exit loop and method
        }
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      console.error(`[BatchService] Error in chat continuation for batchChatId ${batchChatId}:`, {
        message: errorMessage,
        stack: error instanceof Error ? error.stack : undefined,
        name: error instanceof Error ? error.name : undefined,
        cause: error instanceof Error ? error.cause : undefined
      });
      await this.updateBatchChatStatus(batchChatId, BatchChatStatus.FAILED);
    }
  }

  /**
   * Updates a batch chat's status and possibly starts a new chat
   */
  async updateBatchChatStatus(batchChatId: string, status: BatchChatStatus) {
    try {
      const batchChat = await prisma.batchChat.findUnique({
        where: { id: batchChatId },
        include: { batch: true },
      });
  
      if (!batchChat) {
        throw new Error(`BatchChat not found: ${batchChatId}`);
      }
  
      // Update the batch chat status
      await prisma.batchChat.update({
        where: { id: batchChatId },
        data: { status },
      });
  
      // If this chat completed or failed, update counters and possibly start next chat
      if (status === BatchChatStatus.COMPLETED || status === BatchChatStatus.FAILED) {
        const batchId = batchChat.batch.id;

        // 1. Update the batch with atomic increment of completedChats
        const updatedBatch = await prisma.chatBatch.update({
          where: { id: batchId },
          data: {
            completedChats: { increment: 1 }
          }
        });

        // 2. Use the in-memory tracker for concurrency decisions (race-safe).
        //    Lazy-initialize from DB state if not already created (e.g., after
        //    server restart, or if updateBatchChatStatus is called before startBatch).
        //    Once initialized, all synchronous decisions on the tracker are safe
        //    because JS is single-threaded.
        const batch = batchChat.batch;

        if (!BatchService.batchTrackers.has(batchId)) {
          // First time seeing this batch in this process — seed from DB
          const batchWithCount = await prisma.chatBatch.findUnique({
            where: { id: batchId },
            include: { _count: { select: { batchChats: true } } }
          });
          const dbCreatedCount = batchWithCount?._count?.batchChats ?? batch.totalChats;
          // Estimate running = created - completed (approximate, but safe for first init)
          const estimatedRunning = Math.max(0, dbCreatedCount - updatedBatch.completedChats);
          this.getOrCreateTracker(batchId, batch.totalChats, dbCreatedCount);
          const newTracker = BatchService.batchTrackers.get(batchId)!;
          newTracker.running = estimatedRunning;
        }
        const tracker = BatchService.batchTrackers.get(batchId)!;

        // Synchronously release the running slot — can't race
        tracker.running = Math.max(0, tracker.running - 1);

        // Check if batch is done
        if (updatedBatch.completedChats >= updatedBatch.totalChats) {
          await prisma.chatBatch.update({
            where: { id: batchId },
            data: { status: BatchStatus.COMPLETED },
          });
          this.cleanupTracker(batchId);
          return;
        }

        // Check if batch was cancelled
        if (batch.status === BatchStatus.CANCELLED) {
          this.cleanupTracker(batchId);
          return;
        }

        // Check if we can and should start a new chat.
        // Both checks are synchronous reads — no async gap for races.
        const concurrencyLimit = 5;
        if (tracker.created < tracker.totalTarget && tracker.running < concurrencyLimit) {
          // Synchronously claim the slot BEFORE the async call
          tracker.created++;
          tracker.running++;
          const nextSequenceNumber = tracker.created;

          this.startBatchChat({
            batchId,
            configId: batch.configId,
            userId: batch.userId,
            sequenceNumber: nextSequenceNumber,
          }).catch(err => {
            // Release the slot on failure so the chain can recover
            const t = BatchService.batchTrackers.get(batchId);
            if (t) t.running = Math.max(0, t.running - 1);
            const errorMessage = err instanceof Error ? err.message : String(err);
            console.error(`Error starting next chat #${nextSequenceNumber}: ${errorMessage}`);
          });
        }
      }
    } catch (error) {
      console.error('Error in updateBatchChatStatus:', error instanceof Error ? error.message : String(error));
      // We don't re-throw as this would break the chain of chat processing
    }
  }

  /**
   * Cancels a batch
   */
  async cancelBatch(batchId: string) {
    if (!batchId) {
      throw new Error('No batch ID provided for cancellation');
    }
    
    try {
      // Check if batch exists
      const batchExists = await prisma.chatBatch.findUnique({
        where: { id: batchId },
        select: { id: true }
      });
      
      if (!batchExists) {
        throw new Error(`Cannot cancel batch: batch with ID ${batchId} not found`);
      }
      
      // Update batch status to CANCELLED
      await prisma.chatBatch.update({
        where: { id: batchId },
        data: { status: 'CANCELLED' },
      });
      
      // Update all RUNNING batch chats to CANCELLED
      await prisma.batchChat.updateMany({
        where: {
          batchId,
          status: 'RUNNING'
        },
        data: {
          status: 'CANCELLED'
        },
      });

      // Clean up in-memory tracker
      this.cleanupTracker(batchId);

      return true;
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      console.error(`[BatchService] Error cancelling batch ${batchId}:`, errorMessage);
      throw error;
    }
  }

  /**
   * Gets a batch by ID
   */
  async getBatch(batchId: string) {
    const batch = await prisma.chatBatch.findUnique({
      where: { id: batchId },
      include: {
        batchChats: {
          include: {
            chat: {
              select: {
                id: true,
                title: true
              }
            },
          },
          orderBy: { createdAt: 'desc' },
        },
      },
    });

    // Add the chat title to the batchChats for display
    if (batch) {
      batch.batchChats = batch.batchChats.map(batchChat => ({
        ...batchChat,
        name: batchChat.chat?.title || undefined
      }));
    }

    return batch;
  }

  /**
   * Gets all batches for a config
   */
  async getBatchesByConfig(configId: string) {
    return prisma.chatBatch.findMany({
      where: { configId },
      orderBy: { createdAt: 'desc' },
      include: {
        _count: {
          select: { batchChats: true },
        },
      },
    });
  }
} 